//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer1 : DbContext
    {
        public DataModelContainer1()
            : base("name=DataModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TeamsEntity> TeamsEntitySet { get; set; }
        public virtual DbSet<UsersEntity> UsersEntitySet { get; set; }
        public virtual DbSet<TasksEntity> TasksEntitySet { get; set; }
    }
}
