//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public Tasks()
        {
            this.Users = new HashSet<Users>();
        }
    
        public int TaskId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<Users> Users { get; set; }
    }
}
