//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsEntity
    {
        public TeamsEntity()
        {
            this.UsersEntity = new HashSet<UsersEntity>();
        }
    
        public int TeamId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UsersEntity> UsersEntity { get; set; }
    }
}
