//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersEntity
    {
        public UsersEntity()
        {
            this.TasksEntity = new HashSet<TasksEntity>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public short Role { get; set; }
        public short Seniority { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Password { get; set; }
        public int TeamsEntityTeamId { get; set; }
    
        public virtual TeamsEntity TeamsEntity { get; set; }
        public virtual ICollection<TasksEntity> TasksEntity { get; set; }
    }
}
